version: 0.2

# env:
#     parameter-store:
#         AWS_ACCESS_KEY_ID_PARAM: Access_Key_Id
#         AWS_SECRET_ACCESS_KEY_PARAM: Secret_access_key
#         AWS_SESSION_TOKEN_PARAM: session_token

    
phases:
  install:
    commands:
      - echo Entered the install terraform
      - "apt-get install zip unzip -y" # install unzip
      - "wget https://releases.hashicorp.com/terraform/1.1.0-alpha20211006/terraform_1.1.0-alpha20211006_linux_amd64.zip"
      - "unzip terraform_1.1.0-alpha20211006_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - ASSUME_ROLE_ARN="arn:aws:iam::117005682321:role/service-role/AWSCodePipelineServiceRole-us-east-1-pipeline-test"

      
      

  pre_build:
    commands:
      - terraform --version
      # - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PARAM
      # - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PARAM
      # - export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_PARAM
      - terraform init 
    

  build:
    commands:
      - terraform $TF_COMMAND -auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND complete on 'date' 
      - echo soho is having fun at Diligent    